/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'recent_transactions' : Array<
    { 'id' : bigint, 'item' : string, 'time' : string, 'amount' : number }
  >,
  'monthly_sales' : number,
  'weekly_sales' : number,
  'total_revenue' : number,
  'top_sellers' : Array<
    { 'revenue' : number, 'name' : string, 'units_sold' : bigint }
  >,
  'daily_sales' : number,
  'total_profit' : number,
}
export interface Ingredient {
  'id' : IngredientId,
  'updated_at' : bigint,
  'cost_price' : number,
  'low_stock_threshold' : number,
  'supplier' : string,
  'name' : string,
  'unit' : string,
  'created_at' : bigint,
  'quantity' : number,
}
export type IngredientId = bigint;
export interface Notification {
  'id' : NotificationId,
  'is_read' : boolean,
  'type' : string,
  'created_at' : bigint,
  'message' : string,
}
export type NotificationId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addIngredient' : ActorMethod<
    [string, number, string, number, string, number],
    IngredientId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteIngredient' : ActorMethod<[IngredientId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getIngredient' : ActorMethod<[IngredientId], Ingredient>,
  'getIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getLowStockIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getTotalInventoryValue' : ActorMethod<[], number>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedIngredients' : ActorMethod<[], undefined>,
  'updateIngredient' : ActorMethod<
    [IngredientId, string, number, string, number, string, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];