/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'recent_transactions' : Array<
    { 'id' : bigint, 'item' : string, 'time' : string, 'amount' : number }
  >,
  'monthly_sales' : number,
  'weekly_sales' : number,
  'total_revenue' : number,
  'top_sellers' : Array<
    { 'revenue' : number, 'name' : string, 'units_sold' : bigint }
  >,
  'daily_sales' : number,
  'total_profit' : number,
}
export interface Ingredient {
  'id' : IngredientId,
  'updated_at' : bigint,
  'cost_price' : number,
  'low_stock_threshold' : number,
  'supplier' : string,
  'name' : string,
  'unit' : string,
  'created_at' : bigint,
  'quantity' : number,
}
export type IngredientId = bigint;
export interface IngredientUsage {
  'quantity_used' : number,
  'ingredientName' : string,
}
export interface MenuItem {
  'id' : MenuItemId,
  'updated_at' : bigint,
  'name' : string,
  'selling_price' : number,
  'description' : string,
  'created_at' : bigint,
  'ingredientUsage' : Array<IngredientUsage>,
  'cost_per_bowl' : number,
}
export type MenuItemId = bigint;
export interface Notification {
  'id' : NotificationId,
  'is_read' : boolean,
  'type' : string,
  'created_at' : bigint,
  'message' : string,
}
export type NotificationId = bigint;
export interface ReportStats {
  'total_units' : bigint,
  'total_orders' : bigint,
  'total_revenue' : number,
  'top_sellers' : Array<
    { 'revenue' : number, 'name' : string, 'units_sold' : bigint }
  >,
  'avg_order_value' : number,
  'daily_breakdown' : Array<
    {
      'revenue' : number,
      'orders' : bigint,
      'profit' : number,
      'date_label' : string,
    }
  >,
  'total_profit' : number,
}
export type SaleId = bigint;
export interface SaleRecord {
  'id' : SaleId,
  'total_amount' : number,
  'cost_amount' : number,
  'menu_item_name' : string,
  'created_at' : bigint,
  'unit_price' : number,
  'quantity' : bigint,
  'profit' : number,
  'menu_item_id' : MenuItemId,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addIngredient' : ActorMethod<
    [string, number, string, number, string, number],
    IngredientId
  >,
  'addMenuItem' : ActorMethod<
    [string, string, number, number, Array<IngredientUsage>],
    MenuItemId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteIngredient' : ActorMethod<[IngredientId], undefined>,
  'deleteMenuItem' : ActorMethod<[MenuItemId], undefined>,
  'deleteSale' : ActorMethod<[SaleId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getIngredient' : ActorMethod<[IngredientId], Ingredient>,
  'getIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getLowStockIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getMenuItem' : ActorMethod<[MenuItemId], MenuItem>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getReportStats' : ActorMethod<[bigint, bigint], ReportStats>,
  'getSaleById' : ActorMethod<[SaleId], SaleRecord>,
  'getSales' : ActorMethod<[], Array<SaleRecord>>,
  'getSalesByDateRange' : ActorMethod<[bigint, bigint], Array<SaleRecord>>,
  'getTotalInventoryValue' : ActorMethod<[], number>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'recordSale' : ActorMethod<[MenuItemId, bigint], SaleId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedIngredients' : ActorMethod<[], undefined>,
  'seedMenuItems' : ActorMethod<[], undefined>,
  'updateIngredient' : ActorMethod<
    [IngredientId, string, number, string, number, string, number],
    undefined
  >,
  'updateMenuItem' : ActorMethod<
    [MenuItemId, string, string, number, number, Array<IngredientUsage>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];