/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const IngredientId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'recent_transactions' : IDL.Vec(
    IDL.Record({
      'id' : IDL.Nat,
      'item' : IDL.Text,
      'time' : IDL.Text,
      'amount' : IDL.Float64,
    })
  ),
  'monthly_sales' : IDL.Float64,
  'weekly_sales' : IDL.Float64,
  'total_revenue' : IDL.Float64,
  'top_sellers' : IDL.Vec(
    IDL.Record({
      'revenue' : IDL.Float64,
      'name' : IDL.Text,
      'units_sold' : IDL.Nat,
    })
  ),
  'daily_sales' : IDL.Float64,
  'total_profit' : IDL.Float64,
});
export const Ingredient = IDL.Record({
  'id' : IngredientId,
  'updated_at' : IDL.Int,
  'cost_price' : IDL.Float64,
  'low_stock_threshold' : IDL.Float64,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'created_at' : IDL.Int,
  'quantity' : IDL.Float64,
});
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'is_read' : IDL.Bool,
  'type' : IDL.Text,
  'created_at' : IDL.Int,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addIngredient' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
      [IngredientId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteIngredient' : IDL.Func([IngredientId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getIngredient' : IDL.Func([IngredientId], [Ingredient], ['query']),
  'getIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getLowStockIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getTotalInventoryValue' : IDL.Func([], [IDL.Float64], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedIngredients' : IDL.Func([], [], []),
  'updateIngredient' : IDL.Func(
      [
        IngredientId,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Float64,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const IngredientId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'recent_transactions' : IDL.Vec(
      IDL.Record({
        'id' : IDL.Nat,
        'item' : IDL.Text,
        'time' : IDL.Text,
        'amount' : IDL.Float64,
      })
    ),
    'monthly_sales' : IDL.Float64,
    'weekly_sales' : IDL.Float64,
    'total_revenue' : IDL.Float64,
    'top_sellers' : IDL.Vec(
      IDL.Record({
        'revenue' : IDL.Float64,
        'name' : IDL.Text,
        'units_sold' : IDL.Nat,
      })
    ),
    'daily_sales' : IDL.Float64,
    'total_profit' : IDL.Float64,
  });
  const Ingredient = IDL.Record({
    'id' : IngredientId,
    'updated_at' : IDL.Int,
    'cost_price' : IDL.Float64,
    'low_stock_threshold' : IDL.Float64,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'created_at' : IDL.Int,
    'quantity' : IDL.Float64,
  });
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'is_read' : IDL.Bool,
    'type' : IDL.Text,
    'created_at' : IDL.Int,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addIngredient' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
        [IngredientId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteIngredient' : IDL.Func([IngredientId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getIngredient' : IDL.Func([IngredientId], [Ingredient], ['query']),
    'getIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getLowStockIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getTotalInventoryValue' : IDL.Func([], [IDL.Float64], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedIngredients' : IDL.Func([], [], []),
    'updateIngredient' : IDL.Func(
        [
          IngredientId,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Float64,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };